font_family JetBrainsMono Nerd Font
font_size 12.0

window_padding_width 16
background_opacity 0.95
background_blur 16
dynamic_background_opacity yes
confirm_os_window_close 0
enable_audio_bell no
cursor_shape beam

background #05070d
foreground #dcebff
selection_background #111a2e
selection_foreground #dcebff
cursor #00e5ff
cursor_text_color #05070d
url_color #77b6e1

active_border_color #00e5ff
inactive_border_color #4d6fb7
active_tab_foreground #00e5ff
active_tab_background #111a2e
inactive_tab_foreground #8193ab
inactive_tab_background #0a1020
tab_bar_background #05070d

color0 #0a1020
color1 #d64f68
color2 #3aaf8f
color3 #c59e55
color4 #567bc0
color5 #8d78d1
color6 #00a9bd
color7 #a9bed8
color8 #8193ab
color9 #ff637f
color10 #4dd4ac
color11 #f2c66d
color12 #77b6e1
color13 #b29cff
color14 #00e5ff
color15 #dcebff

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
