general {
    hide_cursor = true
}

background {
    monitor =
    path = /etc/nixos-rice/wallpaper.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
}

input-field {
    monitor =
    size = 340, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.24
    dots_center = true
    outer_color = rgba(00e5ffee)
    inner_color = rgba(0a1020dd)
    font_color = rgba(dcebffff)
    check_color = rgba(77b6e1ee)
    fail_color = rgba(ff637fee)
    fade_on_empty = false
    placeholder_text = <span foreground="##6b7d95">Password</span>
    fail_text = <span foreground="##ff637f">$FAIL <b>($ATTEMPTS)</b></span>
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(dcebffff)
    font_size = 78
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgba(77b6e1ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 55
    halign = center
    valign = center
}
